import { associations } from '#schema/Associations';
import { seedBase } from '#seed/Base';
import { associationId } from '#seed/Ids';

export const associationSeed: Array<typeof associations.$inferInsert> = [
  {
    ...seedBase(),
    id: associationId.fifa,
    name: 'Fédération Internationale de Football Association',
    code: 'FIFA',
    kind: 'GLOBAL',
    governingAssociationId: null,
  },
  {
    ...seedBase(),
    id: associationId.afc,
    name: 'Asian Football Confederation',
    code: 'AFC',
    kind: 'CONTINENTAL',
    governingAssociationId: associationId.fifa,
  },
  {
    ...seedBase(),
    id: associationId.caf,
    name: 'Confederation of African Football',
    code: 'CAF',
    kind: 'CONTINENTAL',
    governingAssociationId: associationId.fifa,
  },
  {
    ...seedBase(),
    id: associationId.concacaf,
    name: 'Confederation of North, Central America and Caribbean Association Football',
    code: 'CONCACAF',
    kind: 'CONTINENTAL',
    governingAssociationId: associationId.fifa,
  },
  {
    ...seedBase(),
    id: associationId.conmebol,
    name: 'South American Football Confederation',
    code: 'CONMEBOL',
    kind: 'CONTINENTAL',
    governingAssociationId: associationId.fifa,
  },
  {
    ...seedBase(),
    id: associationId.ofc,
    name: 'Oceania Football Confederation',
    code: 'OFC',
    kind: 'CONTINENTAL',
    governingAssociationId: associationId.fifa,
  },
  {
    ...seedBase(),
    id: associationId.uefa,
    name: 'Union of European Football Associations',
    code: 'UEFA',
    kind: 'CONTINENTAL',
    governingAssociationId: associationId.fifa,
  },
  {
    ...seedBase(),
    id: associationId.facr,
    name: 'Fotbalová asociace České republiky',
    code: 'CZE',
    kind: 'NATIONAL',
    governingAssociationId: associationId.uefa,
  },
  {
    ...seedBase(),
    id: associationId.pzpn,
    name: 'Polski Związek Piłki Nożnej',
    code: 'POL',
    kind: 'NATIONAL',
    governingAssociationId: associationId.uefa,
  },
  {
    ...seedBase(),
    id: associationId.szf,
    name: 'Slovenský futbalový zväz',
    code: 'SVK',
    kind: 'NATIONAL',
    governingAssociationId: associationId.uefa,
  },
  {
    ...seedBase(),
    id: associationId.ofb,
    name: 'Österreichischer Fußball-Bund',
    code: 'AUT',
    kind: 'NATIONAL',
    governingAssociationId: associationId.uefa,
  },
  {
    ...seedBase(),
    id: associationId.dfb,
    name: 'Deutscher Fußball-Bund',
    code: 'GER',
    kind: 'NATIONAL',
    governingAssociationId: associationId.uefa,
  },
];
