import { teams } from '#schema/Teams';
import { seedBase } from '#seed/Base';
import { teamId } from '#seed/Ids';

export const teamSeed: Array<typeof teams.$inferInsert> = [
  {
    ...seedBase(),
    id: teamId.austria,
    name: 'Austria',
    kind: 'NATIONAL',
    country: 'AUT',
    establishedOn: '2026-01-01',
  },
  {
    ...seedBase(),
    id: teamId.czechia,
    name: 'Czechia',
    kind: 'NATIONAL',
    country: 'CZE',
    establishedOn: '2026-01-01',
  },
  {
    ...seedBase(),
    id: teamId.germany,
    name: 'Germany',
    kind: 'NATIONAL',
    country: 'GER',
    establishedOn: '2026-01-01',
  },
  {
    ...seedBase(),
    id: teamId.poland,
    name: 'Poland',
    kind: 'NATIONAL',
    country: 'POL',
    establishedOn: '2026-01-01',
  },
  {
    ...seedBase(),
    id: teamId.slovakia,
    name: 'Slovakia',
    kind: 'NATIONAL',
    country: 'SVK',
    establishedOn: '2026-01-01',
  },
  {
    ...seedBase(),
    id: teamId.slovacko,
    name: '1.FC Slovácko',
    kind: 'CLUB',
    country: 'CZE',
    establishedOn: '2026-01-01',
  },
  {
    ...seedBase(),
    id: teamId.branik,
    name: 'ABC Braník',
    kind: 'CLUB',
    country: 'CZE',
    establishedOn: '2026-01-01',
  },
  {
    ...seedBase(),
    id: teamId.sparta,
    name: 'AC Sparta Praha',
    kind: 'CLUB',
    country: 'CZE',
    establishedOn: '2026-01-01',
  },
  {
    ...seedBase(),
    id: teamId.spartaB,
    name: 'AC Sparta Praha B',
    kind: 'CLUB',
    country: 'CZE',
    establishedOn: '2026-01-01',
  },
  {
    ...seedBase(),
    id: teamId.banik,
    name: 'FC Baník Ostrava',
    kind: 'CLUB',
    country: 'CZE',
    establishedOn: '2026-01-01',
  },
  {
    ...seedBase(),
    id: teamId.hradec,
    name: 'FC Hradec Králové',
    kind: 'CLUB',
    country: 'CZE',
    establishedOn: '2026-01-01',
  },
  {
    ...seedBase(),
    id: teamId.liberec,
    name: 'FC Slovan Liberec',
    kind: 'CLUB',
    country: 'CZE',
    establishedOn: '2026-01-01',
  },
  {
    ...seedBase(),
    id: teamId.liberecB,
    name: 'FC Slovan Liberec B',
    kind: 'CLUB',
    country: 'CZE',
    establishedOn: '2026-01-01',
  },
  {
    ...seedBase(),
    id: teamId.plzen,
    name: 'FC Viktora Plzeň',
    kind: 'CLUB',
    country: 'CZE',
    establishedOn: '2026-01-01',
  },
  {
    ...seedBase(),
    id: teamId.plzenB,
    name: 'FC Viktoria Plzeň B',
    kind: 'CLUB',
    country: 'CZE',
    establishedOn: '2026-01-01',
  },
  {
    ...seedBase(),
    id: teamId.pardubice,
    name: 'FK Pardubice',
    kind: 'CLUB',
    country: 'CZE',
    establishedOn: '2026-01-01',
  },
  {
    ...seedBase(),
    id: teamId.teplice,
    name: 'FK Teplice',
    kind: 'CLUB',
    country: 'CZE',
    establishedOn: '2026-01-01',
  },
  {
    ...seedBase(),
    id: teamId.jihlava,
    name: 'FKM Vysočina Jihlava',
    kind: 'CLUB',
    country: 'CZE',
    establishedOn: '2026-01-01',
  },
  {
    ...seedBase(),
    id: teamId.lokomotiva,
    name: 'Lokomotiva Brno Horní Heršpice',
    kind: 'CLUB',
    country: 'CZE',
    establishedOn: '2026-01-01',
  },
  {
    ...seedBase(),
    id: teamId.pragueRaptors,
    name: 'Prague Raptors FC',
    kind: 'CLUB',
    country: 'CZE',
    establishedOn: '2026-01-01',
  },
  {
    ...seedBase(),
    id: teamId.artis,
    name: 'SK Artis Brno',
    kind: 'CLUB',
    country: 'CZE',
    establishedOn: '2026-01-01',
  },
  {
    ...seedBase(),
    id: teamId.dynamo,
    name: 'SK Dynamo České Budějovice',
    kind: 'CLUB',
    country: 'CZE',
    establishedOn: '2026-01-01',
  },
  {
    ...seedBase(),
    id: teamId.sigma,
    name: 'SK Sigma Olomouc',
    kind: 'CLUB',
    country: 'CZE',
    establishedOn: '2026-01-01',
  },
  {
    ...seedBase(),
    id: teamId.slavia,
    name: 'SK Slavia Praha',
    kind: 'CLUB',
    country: 'CZE',
    establishedOn: '2026-01-01',
  },
];
